/* Generado desde data/agentes-us3.json — no editar a mano */
window.US3_LICENCIAS_DEFAULT = [
  {
    "id": 1,
    "nombre": "Alluchon Agostina",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 2,
    "nombre": "Aranda German",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 3,
    "nombre": "Arroyo Romina",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 4,
    "nombre": "Begino Monserrat",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 5,
    "nombre": "Benetti Marina",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 6,
    "nombre": "Berdun Gonzalo",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 7,
    "nombre": "Bigolin Lorena",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 8,
    "nombre": "Bonaventura Franco",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 9,
    "nombre": "Carrera Maria Lorena",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 10,
    "nombre": "De La Barra Sandra",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 11,
    "nombre": "Giachini Juan",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 12,
    "nombre": "Lespiaucq Paula",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 13,
    "nombre": "Macarrone Marcelo",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 14,
    "nombre": "Marcatelli Genoveva",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 15,
    "nombre": "Masuelli Soledad",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 16,
    "nombre": "Montenegro Walter",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 17,
    "nombre": "Pena Agustina",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 18,
    "nombre": "Rebecchini Genaro",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 19,
    "nombre": "Rodriguez Andres",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 20,
    "nombre": "Rovera Matias",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 21,
    "nombre": "Salama Linda Silvina",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 22,
    "nombre": "Solis Javier",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 23,
    "nombre": "Vergara Diego",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 24,
    "nombre": "Zabala Roberto",
    "esMedico": false,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  },
  {
    "id": 25,
    "nombre": "Zalazar Ariel",
    "esMedico": true,
    "tramo": 1,
    "desde": "2026-10-01",
    "hasta": "2026-10-01",
    "tomados": 0,
    "restan": 0,
    "estado": "pendiente",
    "notas": ""
  }
];
